### ISSUE TITLE
need to click two times on clip to be able to paste it. 

### ISSUE THREAD

**Issue by tuxedotje** [Tudmotu/gnome-shell-extension-clipboard-indicator#209] opened 2020-04-25 19:25 UTC
need to click two times on clip to be able to paste it. 
Fedora 31

**Comment by elpraga** [comment] 2020-04-28 19:53
Yes, I am having the same issue on Ubuntu 20.04 Gnome 3.36 running on Wayland.

Any ideas why that might be happening and how to fix that?

**Comment by elpraga** [comment] 2020-04-28 19:55
Seems to be a duplicate of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/198

**Comment by elpraga** [comment] 2020-05-01 12:19
Seems to be fixed now in Ubuntu 20.04

**Comment by Tudmotu** [comment] 2020-05-03 20:19
Closing, see discussing in #198. You can thank @rmader :)

**Closed by Tudmotu** 2020-05-03 20:19 UTC
