### ISSUE TITLE
Favorites gone when GNOME Shell crashing

### ISSUE THREAD

**Issue by orschiro** [Tudmotu/gnome-shell-extension-clipboard-indicator#127] opened 2018-06-04 12:09 UTC
Hey there, 

Does anyone else have this problem?

Whenever Shell crashes, I am losing all my history, and even worse, all my favorites. :-(

Is there anything we can do to prevent losing favorites when Shell crashes?

Looking forward!

Thank you...

**Comment by Filbuntu** [comment] 2019-08-25 05:58
My favorites are also often gone, even without losing the whole history. It may even happen without a Shell crash. I have to monitor it.

**Comment by SUPERCILEX** [comment] 2022-01-09 06:44
Duplicate of #229

**Closed** 2023-10-19 12:08 UTC
