### ISSUE TITLE
"Text will be here" is displayed in the tray and nothing happens by clicking on it.

### ISSUE THREAD

**Issue by BuZZ-dEE** [Tudmotu/gnome-shell-extension-clipboard-indicator#459] opened 2024-04-09 10:19 UTC
"Hier erscheint der Text" or "Text will be here" is displayed in the tray and nothing happens by clicking on it.

OS: Arch Linux x86_64
DE: Gnome 46 on Wayland
Extension version: 61

**Comment by sounddrill31** [comment] 2024-04-09 10:40
+1

> "Hier erscheint der Text" or "Text will be here" is displayed in the tray and nothing happens by clicking on it.
> 
> OS: Arch Linux x86_64 DE: Gnome 46 on Wayland Extension version: 61

OS: OpenSUSE Tumbleweed with 6.8.4
DE: Gnome 46 with wayland
Extension Version: 61

**Comment by MeirKriheli** [comment] 2024-04-09 10:49
@sounddrill31 Thanks, deleting the cache and re-enabling the extension helped here as well.

**Comment by Tudmotu** [comment] 2024-04-09 14:38
Possibly related to this?
https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/458

**Comment by Tudmotu** [comment] 2024-04-09 18:49
Can everyone here please try updating to version 62 and see if it fixes the issue for you?

Thanks! :pray:

**Comment by tanjilbhuiyan** [comment] 2024-04-09 20:11
Thanks, it seems the issue is fixed. But faced a weird issue. i uninstalled previous one. then installed again. Got error in Gnome extension page. though the extension was downloaded. Had to log out and log in again. It seems working now.

**Comment by Tudmotu** [comment] 2024-04-10 05:48
Thank you for testing it out @tanjilbhuiyan !

To update the extension you must log out and back in. This is true every time you update — it only updates after the next login.

**Comment by sounddrill31** [comment] 2024-04-10 06:34
Works so far for me!

Thanks for the fix

**Comment by arturo-source** [comment] 2024-04-10 06:51
Hello @Tudmotu,
I had the same problem when I updated to 61, then I updated to 62 and the problem kept. 
Unfortunately I already deleted cache, as @sounddrill31 recommended and it started working again, so I cannot test anymore.

**Comment by Tudmotu** [comment] 2024-04-10 07:14
Thank you for confirming @sounddrill31 !

@arturo-source apologies you had to remove your cache file 😕 Hope this won't have to happen again but if it does, next time I recommend renaming the file instead of deleting it, so that you can restore it later on.

**Comment by MeirKriheli** [comment] 2024-04-10 13:44
Same here: removed the cache (was not that important anyway), so can't check.

**Comment by DerPate** [comment] 2024-04-12 07:39
@Tudmotu can confirm the update to Version 62 fixed the problem for me

**Comment by Tudmotu** [comment] 2024-04-12 14:18
Thanks everyone, closing this issue :slightly_smiling_face:

**Comment by dmnmsc** [comment] 2024-04-12 19:40
This is still present here. Extension version 62. Archlinux up-to-date with wayland session.

**Comment by tanjilbhuiyan** [comment] 2024-04-15 08:03
Clear the cache mentioned by @sounddrill31 . Things should work.

**Comment by dmnmsc** [comment] 2024-04-16 20:58
But @Tudmotu said this should work without deleting cache. I'm just reporting the bug :)

**Comment by AmeyaVS** [comment] 2024-04-26 05:54
Same here on Fedora 40 after updating the system.
I backed up my `.cache` as I still use some of the clipboard data.
Clearing the directory does work, but then I loose all the clipboard data.

**Comment by AmeyaVS** [comment] 2024-04-28 05:13
I changed the `UTF8_STRING` to `text/plain` type, and reloaded the extension it seems to work.
Can  this issue be reopened @Tudmotu ?

**Comment by djfjeff** [comment] 2024-05-17 10:59
I have the same problem using the latest version on Fedora 40. Sometime, the issue arise and I need to clear cache for it to work again. Please reopen as this is definitely not solved.

**Comment by Tudmotu** [comment] 2024-05-21 17:59
Reopening.
Can anyone clarify the step to reproduce this issue?
1. Delete cache file
2. Copy some stuff
3. Log out, log in
4. Clipboard is broken?

**Comment by djfjeff** [comment] 2024-05-21 18:01
It seems random on my end. Sometime when I unlock my session, I get the "Text will be here" issue, most of the time everything is alright...

I then delete the cache file and restart the extension and I am good for a while.

**Comment by alephnull** [comment] 2024-05-30 07:28
What worked for me:
- change `UTF8_STRING` in `~/.cache/clipboard-indicator@tudmotu.com/registry.txt` to `text/plain;charset=utf-8` 
- disable and enable the extension
It appears to be a problem only on Wayland.

**Comment by HeroBrine1st** [comment] 2024-05-30 07:43
> It appears to be a problem only on Wayland.

No, it doesn't. Also I did not have UTF8_STRING in that file, I had to remove that folder to fix extension instead. 
I am on NixOS unstable with GNOME 46.1 via X11+nvidia.

**Comment by ewh** [comment] 2024-06-06 15:15
I'm using Ubuntu 23.10, Gnome 45.2, Wayland. I'm using Clipboard Indicator 57 (installed from extensions.gnome.org). Version 57 seems to be the latest version on extensions.gnome.org for Gnome 45. Should the "Text will be here" issue be fixed in version 57. If not, will version 62 work correctly in Gnome 45?

**Comment by rebelinux** [comment] 2024-06-14 20:15
> What worked for me:
> 
> * change `UTF8_STRING` in `~/.cache/clipboard-indicator@tudmotu.com/registry.txt` to `text/plain;charset=utf-8`
> * disable and enable the extension
>   It appears to be a problem only on Wayland.

Solution works for me.  thanks!

**Comment by Snorch** [comment] 2024-06-21 02:50
If someone still experiences the problem on latest master, please give a try to https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/480 and say if it helps or not. (Probably you need to fully reboot to properly reload extension.)

It looks like just doing replacement in registry.txt didn't fix the problem completely, at least for me, as UTF8_STRING continues to appear there again and again (I see it appearing when I'm actively copying between Firefox and Tilix in both directions).

It also looks that the problem has other manifestation: sometimes the entries with mimetype==UTF8_STRING just silently disappear instead of causing the 'stuck extension' problem mentioned in this issue.

**Comment by ma0shu** [comment] 2024-06-23 06:06
> If someone still experiences the problem on latest master, please give a try to #480 and say if it helps or not. (Probably you need to fully reboot to properly reload extension.)
> 
> It looks like just doing replacement in registry.txt didn't fix the problem completely, at least for me, as UTF8_STRING continues to appear there again and again (I see it appearing when I'm actively copying between Firefox and Tilix in both directions).
> 
> It also looks that the problem has other manifestation: sometimes the entries with mimetype==UTF8_STRING just silently disappear instead of causing the 'stuck extension' problem mentioned in this issue.

#480 Works fine for me, thx

**Closed** 2024-07-12 10:58 UTC
