### ISSUE TITLE
Gnome 3.32.2 Cause lags on every TIMEOUT updated

### ISSUE THREAD

**Issue by fdinardo** [Tudmotu/gnome-shell-extension-clipboard-indicator#158] opened 2019-05-31 15:18 UTC
I noticed that every time the extension updates the cache, everything lags:
Mouse, writing, video, whatever is running gets paused, like a little freeze.

@Tudmotu 
Look like this extension has not been updated since 3.26 -looking at `metadata.json`-. 
Is it dropped?

**Comment by Tudmotu** [comment] 2019-06-01 10:27
I don't see an issue on 3.32.1, which is the latest stable version. I don't know why you have 3.32.2, but maybe it's an issue with that version that will be fixed when released?

The reason metadata.json is not updated is because it is not necessary anymore. In the past, Gnome required you to update the metadata.json, but it caused many extensions to just stop working, so they removed that requirement.

**Comment by fdinardo** [comment] 2019-06-01 19:13
Hi, thanks for the answer.
I run this version because archlinux matches the last tag: [here](https://gitlab.gnome.org/GNOME/gnome-shell/commit/0ada312748df038a818ff573ba5b5bc341c7fb23)

I don't think it's related to 3.32.2 because the gnome-shell changes are very small, but at the same time I have to be hones, and before updating to 32.2 I didn't have any issues. 

Anyway when I disable `clipboard-indicator` extension I don't get any lag.

There is another user [here](https://extensions.gnome.org/extension/779/clipboard-indicator/) that said that same thing.

I am sorry if I ask you this, I am not an expert, but can this be related to the new ES6 syntax that gnome released with 3.32??

thanks.

**Comment by Tudmotu** [comment] 2019-06-02 06:59
OK, I see 3.32.2 was released a couple days ago on Arch, I guess the mirrors I use didn't update yet. Will check it out. Thanks for letting me know :)

Sometimes these issues are bugs in Gnome Shell, these things happen. Don't know about the ES6 changes, but could also be that some API has changed. In any case, I will take a look.

**Comment by fdinardo** [comment] 2019-06-03 11:49
Thanks for the answer. Feel free to close this issue when you are ready to. 
Thanks

**Comment by RussianNeuroMancer** [comment] 2019-08-10 09:33
This issue is still reproducible for me, with Gnome Shell 3.32.2 too (on Ubuntu 19.10).

**Comment by tmahmood** [comment] 2019-10-23 05:07
The issue still exists on my computer, Gnome shell 3.34. Had to disable

**Comment by b00f** [comment] 2020-03-27 12:39
This is my experience. First of all it's not happening all the times. I can see when the CPU is engaged with some debugger or heavy stuff the chance of lagging is high. 
My screen gets freeze and lags when I cut a line (Ctrl+X). After a second freezing, it cuts more than 10 lines. 
I disabled the extension and never saw this bizarre behaviors any more. Hope this help to fix this issue.
This extension is amazing and very useful but this issue is something on the nerve!

**Comment by SUPERCILEX** [comment] 2022-02-22 06:46
Hey folks, this should be fixed in a re-written version of the extension: https://github.com/SUPERCILEX/gnome-clipboard-history.

**Closed** 2023-10-19 12:04 UTC
