### ISSUE TITLE
SyntaxError: import declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by CrossedCarpet** [Tudmotu/gnome-shell-extension-clipboard-indicator#419] opened 2023-11-21 14:00 UTC
The settings of extension clipboard-indicator@tudmotu.com had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:5:19
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Tudmotu** [comment] 2023-11-22 13:50
Closing as duplicate of #416

**Closed by Tudmotu** 2023-11-22 13:50 UTC
