### ISSUE TITLE
Pasting in vim does not work

### ISSUE THREAD

**Issue by hari-rangarajan** [Tudmotu/gnome-shell-extension-clipboard-indicator#59] opened 2017-01-18 01:03 UTC
[Not sure if there are any vim users here ]

The "+" register usually has the clipboard contents. After cycling through entries with the extension, it ends up empty. Gedit does work correctly. Wonder if you investigated this?

Thanks

**Comment by Tudmotu** [comment] 2017-01-18 13:26
Thanks for reporting!
I personally use vim, and can confirm this does not work for some reason. Don't really know why, though.

I'll try to investigate, but not sure when will I have time to look into it.

Meanwhile, you can use a workaround: in insert mode, use Ctrl+Shift+V
I know it's not as comfortable, and acts a bit differently than "+P, but at least in the meantime.

**Comment by xnaveira** [comment] 2019-04-12 10:54
I can confirm this, doesn't work in gvim either. I use the `set clipboard=unnamedplus` which syncs the vim/gvim clipboard with the system's but when I select something from the extension it doesn't work.

**Comment by deragon** [comment] 2019-04-26 18:42
I confirm this too.  I have opened a [ticket (#4217) against vim](https://github.com/vim/vim/issues/4217) since it is the only application for which Gnome Clipboard indicator is not working with.  They closed it stating the problem must be with Gnome Clipboard indicator.

**Comment by pinnerup** [comment] 2019-11-25 09:11
I'm not sure whether this is the same bug, but I'm unable to paste content from Clipboard Indicator directly into certain text fields in the memorization software Anki.

Specifically it's about input fields created using a new web toolkit; other input fields in the program allow pasting without problems.

**Closed** 2023-10-19 12:05 UTC
