### ISSUE TITLE
Error when try to start extension

### ISSUE THREAD

**Issue by StanislavI22** [Tudmotu/gnome-shell-extension-clipboard-indicator#300] opened 2021-06-28 14:20 UTC
Error: Could not guess unspecified GValue type

Stack trace:
  addKeybinding@/home/user/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:281:5
  _init@/home/user/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:109:9
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
  newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
  buildPrefsWidget@/home/user/.local/share/gnome-shell/extensions/clipboard-indicator@tudmotu.com/prefs.js:257:18
  _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:83:22
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:235:17
  wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:389:5
  @<main>:1:43

**Comment by hjwk** [comment] 2021-07-19 09:56
Duplicate of #296

**Closed** 2021-11-14 13:39 UTC
