### ISSUE TITLE
remmina can cause clipboard to lock desktop?

### ISSUE THREAD

**Issue by jhaar** [Tudmotu/gnome-shell-extension-clipboard-indicator#45] opened 2016-08-17 00:48 UTC
I have been using your extension for ages - love it! However, I've had a continual problem with my gnome-shell "locking up": the mouse moves fine, but focus is lost and I cannot do anything except Ctrl-Alt-F4, log into a tty and try to kill the problem

There's only one situation that leads to this problem. I'm a big user of remmina (ssh and RDP manager) and the only way this problem occurs is when I'm in a remmina session, and I click on my clipboard to grab some line out of history. When the problem occurs, the clipboard dropbox doesn't disappear - it stays present after I attempt to click out of it - and I cannot paste the content into the remmina window, I cannot "swoop" out to change desktops, I cannot change applications, etc. 

By getting onto a tty, I can either "gnome-shell -r" or kill remmina - either fixes the problem.

So far I've been thinking there was some bug in remmina causing this (and reported it as such but it can't be duplicated), but I've suddenly realised the problem _always_ involves clipboard too. So it could be either an interaction between remmina and clipboard - or it actually could be clipboard - and it's just that I spend so much time in my SSH sessions inside remmina, that statistically it "feels like" remmina's involved

Assuming this isn't a known problem, is there anything I could do to try to debug this to find the root cause? I've seen this since Fedora-21 (I'm on Fedora 23 now) with Gnome of course. BTW, this isn't continual, on a good day I can not see this problem - but some days it triggers 2-3 times (and of course in all cases there are hours of me sitting in a remmina session cut-n-pasting out of clipboard without any issues)

Thanks! Living without your extension is NOT an option ;-)

**Comment by Tudmotu** [comment] 2016-08-17 07:18
Very weird. I have no idea on what might be the cause of this. 
If you can somehow consistently reproduce it, it would help a lot :)

**Comment by Tudmotu** [comment] 2018-07-31 08:41
Closing this. If anyone still has issues please open a new ticket.

**Closed by Tudmotu** 2018-07-31 08:41 UTC
