### ISSUE TITLE
need to select twice in clipboard history to get something to paste

### ISSUE THREAD

**Issue by kapouer** [Tudmotu/gnome-shell-extension-clipboard-indicator#198] opened 2020-03-19 10:40 UTC
Hi, on debian/sid, gnome 3.36 on wayland, libgtk 3.24.14:
once copied, i need to select the item twice in clipboard history or else it doesn't paste anything.
Edit: it wasn't really gnome 3.36. It was gnome-shell 3.34.4 / mutter 5.

**Comment by rmader** [comment] 2020-03-30 23:29
Had a first look into this today - looks like it's a shell bug this time. Will try to come up with something soon.

**Comment by kapouer** [comment] 2020-04-04 08:28
Update: same bug on mutter 6 / gnome-shell 3.36

**Comment by antistress** [comment] 2020-04-09 19:11
I can confirm this bug on Debian SId
gnome-shell 3.34.4-1
mutter 3.34.4-1
libgtk-3-0 3.24.14-1
Clipboard Indicator 33
Thanks

**Comment by rmader** [comment] 2020-04-16 22:34
This just got fixed by https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1204, coming to 3.36.2

**Comment by kapouer** [comment] 2020-04-16 22:39
Interesting kind of commit: only removals ;)

**Comment by Filbuntu** [comment] 2020-04-17 06:21
> This just got fixed by https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1204, coming to 3.36.2

Great and thanks! Hopefully Ubuntu 20.04 will get 3.36.2 soon!

**Comment by kapouer** [comment] 2020-04-23 12:38
mutter commit has been cherry-picked and uploaded to debian/sid: now copy/paste works correctly (afaict).

**Comment by elpraga** [comment] 2020-05-01 12:19
I cannot reproduce the need to double click to paste on Ubuntu 20.04 anymore. 

What is strange though is that the clipping preview in the panel changes only when I make a new clipping by pressing Control+C. It **does not** change when I select a different clipping from the list.

Should I file a separate issue?

**Comment by rmader** [comment] 2020-05-01 12:27
Mutter 3.36.2 and 3.34.6 have been released now so we can close the issue.

> What is strange though is that the clipping preview in the panel changes only when I make a new clipping by pressing Control+C. It does not change when I select a different clipping from the list.

Yes, please do. That sounds like a real bug in the extension.

**Comment by Filbuntu** [comment] 2020-05-01 12:30
To all Ubuntu user, please subscribe to [this launchpad bug report](https://bugs.launchpad.net/ubuntu/+source/mutter/+bug/1852183) and hopefully Mutter 3.36.2 will soon arrive in Ubuntu 20.04.

**Comment by Tudmotu** [comment] 2020-05-03 20:18
Thank you @rmader :)

**Closed by Tudmotu** 2020-05-03 20:18 UTC
