### ISSUE TITLE
Screenshot doesn't work

### ISSUE THREAD

**Issue by JasirVoriya** [Tudmotu/gnome-shell-extension-clipboard-indicator#403] opened 2023-10-14 04:50 UTC
After I take a screenshot using the Ubuntu system, the image does not appear in the clipboard history.

**Comment by Tudmotu** [comment] 2023-10-15 10:49
Thank you for reporting this.
Can you please share what version of Ubuntu are you using and what screenshot app are you using?

**Comment by th3me** [comment] 2023-10-16 19:19
I'm on PopOS 22.04 (gnome 42) and storing copied images doesn't work at all. I tried increasing the maximum allowed file size but it had no effect.

**Comment by JasirVoriya** [comment] 2023-10-17 00:59
> Thank you for reporting this. Can you please share what version of Ubuntu are you using and what screenshot app are you using?
OS: Ubuntu 22.04.3 LTS
gonme version: 42.9
I am using the system's built-in screenshot app.

**Comment by Tudmotu** [comment] 2023-10-17 07:29
Unfortunately images are only supported starting with GNOME 45.

Closing this.

**Closed by Tudmotu** 2023-10-17 07:29 UTC

**Comment by livan3li** [comment] 2023-11-21 18:52
hi, @Tudmotu Then if it's not supported can you disable for copying images so that we dont get errors like this. 

![image](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/assets/46044710/716240a2-7cf7-4139-b473-aaf95ba9453d)

**Comment by Tudmotu** [comment] 2023-11-22 13:42
@livan3li I don't think your issue is related.
Can you please open a new issue with the OS you are using, the extension version, and logs from `journalctl -f /bin/gnome-shell`?
Thanks.

**Comment by livan3li** [comment] 2023-11-23 09:15
@Tudmotu Sorry for misunderstanding. I checked again the error hasn't been caused by this extension. It's been different one.

**Comment by Tudmotu** [comment] 2023-11-23 13:16
> @Tudmotu Sorry for misunderstanding. I checked again the error hasn't been caused by this extension. It's been different one.

Cool, thank for the update :slightly_smiling_face:
