### ISSUE TITLE
please update gnome-shell-extension-clipboard-indicator to be compatible with gnome 47 

### ISSUE THREAD

**Issue by githlacker** [Tudmotu/gnome-shell-extension-clipboard-indicator#491] opened 2024-09-19 21:36 UTC

**Comment by mattia-b89** [comment] 2024-09-21 07:19
duplicate of https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/issues/488
please close, so we can focus on it

**Closed** 2024-09-21 07:24 UTC
