### ISSUE TITLE
Expand history size to 9999 (Or at least more than 500)

### ISSUE THREAD

**Issue by luisalvarado** [Tudmotu/gnome-shell-extension-clipboard-indicator#154] opened 2019-04-18 21:54 UTC
Currently the hard history limit of 50 is too small. As a developer, getting to 50 can take just less than 10 minutes and I might need something I copied an hour ago, or yesterday which is typically the case. Raising the limit to 9999 or something higher than 500 would help at many levels.

**Comment by SUPERCILEX** [comment] 2022-02-22 06:41
Duplicate of #222

**Closed** 2023-10-19 12:11 UTC
