### ISSUE TITLE
Broken on Gnome 42 main / 42.beta

### ISSUE THREAD

**Issue by VitalyAnkh** [Tudmotu/gnome-shell-extension-clipboard-indicator#342] opened 2022-02-20 10:40 UTC
After building the latest gnome-shell and gjs, clipboard-indicator reports `Object 0x3acca7228850 is not a subclass of GObject_Object, it's a Object`. Maybe it's caused by the mozjs, which updates from version 78 to version 91.
![image](https://user-images.githubusercontent.com/24508452/154838664-b3f3ad17-66ab-4c8d-85ec-1c452f7693fd.png)

**Comment by taivlam** [comment] 2022-03-24 21:07
I'm also experiencing this issue on Debian Unstable with GNOME.

**Comment by spiffytech** [comment] 2022-03-25 21:23
openSUSE Tumbleweed has rolled out Gnome 42, so this is hitting me.

**Comment by SUPERCILEX** [comment] 2022-03-25 21:34
FYI, I've rewritten this extension and have been told it works on Gnome 42 (though I haven't been able to test it myself): https://github.com/SUPERCILEX/gnome-clipboard-history

**Comment by taivlam** [comment] 2022-04-02 04:10
Alright, I'll give the extension from @SUPERCILEX a try on Debian Unstable with GNOME.  (This extension still works on Pop!_OS, but it's probably because COSMIC is based on GNOME 3.38 and not GNOME 40+ - yet.)

BTW, Is there a way to get the contents of ` gnome-shell-extension-clipboard-indicator` before it stopped working?  It has some contents I'd like to save before migrating over to @SUPERCILEX's extension.

**Comment by SUPERCILEX** [comment] 2022-04-02 07:06
You'll need to copy `.cache/clipboard-indicator@tudmotu.com/registry.txt` to your new OS. Then just install the new extension and your data will be automatically migrated.

**Comment by taivlam** [comment] 2022-04-03 00:36
Thanks for the info!  Although I really should've said I'm first switching GNOME extensions before moving between OS's (from Debian Unstable/Sid to Pop!\_OS) - that'll come later.

If you're wondering whether you have to manually transfer your whether or not your clipboard data will have to manually transferred to SUPERCILEX's extension, you don't.

Upon a new installation, `gnome-clipboard-history` will automatically detect any prior clipboard history from `gnome-shell-extension-clipboard-indicator`.  Amazingly awesome!

**Comment by SUPERCILEX** [comment] 2022-04-03 04:59
Oh gotya, `~/.cache/clipboard-history@alexsaveau.dev/database.log` will be the one to copy then.

**Comment by kdpuvvadi** [comment] 2022-04-05 14:41
just installed clipnoard history from gnome extenstion store, old hostry from this just appead

**Comment by neitsab** [comment] 2022-04-12 15:23
I can confirm that @SUPERCILEX extension works perfectly with GNOME 42 on Arch, and history was directly ported over from this extension. Great work and thanks! 🙏

**Comment by neitsab** [comment] 2022-04-12 15:24
(However, @ccat3z's [GNOME 42 support #348](https://github.com/Tudmotu/gnome-shell-extension-clipboard-indicator/pull/348) didn't: the same error appeared)

**Closed** 2022-04-26 17:28 UTC
