### ISSUE TITLE
The extension isn't working on Wayland

### ISSUE THREAD

**Issue by pedrofleck** [Tudmotu/gnome-shell-extension-clipboard-indicator#208] opened 2020-04-19 21:31 UTC
Hi,
The extension isn't working here on Fedora 31 on a Wayland session. It does keep some information but it's only from XWayland windows and they can only be pasted again on XWayland windows. Does it work on Wayland or there is something wrong on my setup?

**Comment by kapouer** [comment] 2020-04-23 12:37
Duplicate of #198

**Comment by Tudmotu** [comment] 2020-05-03 20:20
Closing, see discussing in #198. You can thank @rmader :)

**Closed by Tudmotu** 2020-05-03 20:20 UTC
