### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by avil25** [Tudmotu/gnome-shell-extension-clipboard-indicator#153] opened 2019-03-27 15:38 UTC
if I click on any text in the clipboard that means I want to paste it. if possible, can this extension directly put the text from the clipboard to the area where I am currently typing the text without pressing ctrl-v

**Comment by capaj** [comment] 2019-04-24 10:36
duplicate of #109

**Closed** 2023-10-19 12:11 UTC
